### ISSUE TITLE
Mistake regarding Karen Vogtmann

### ISSUE THREAD

**Issue by Tom467** [tusindfryd/twenty-female-mathematicians#4]
On the website corresponding to the link for Karen Vogtmann, one of areas of study for Vogtmann is given as 'algebraic K-theory', Vogtmann does not work on K-theory (as far as I am aware), perhaps this was meant to be 'algebraic topology'?

**Comment by tusindfryd** [comment]
Sorry for the late reply. I am not sure if that is a mistake but perhaps changing the research areas to the fields of interest listed in [Vogtmann's CV](https://warwick.ac.uk/fac/sci/maths/people/staff/karen_vogtmann/vitae_sept_2019.pdf) would be a good idea.

**Comment by Tom467** [comment]
I think that would be a good suggestion.  Changing it to 'algebraic topology' would probably be incorrect anyway, as this person's publications indicate that _algebraic_ topology is not strictly speaking one of their research areas.
